Feature/unittests
rtrlib/python-binding pull request #15
Opened 2021-01-06 13:52 UTC by michael-koeller

As I already had a look into this project, I thought I might just as well add some first unit tests.
You'll lanuch them like this:

`> python -m unittest tests`

The deprecated variant is also supported:

`> python setup.py test`
 
Cheers, Michael

2021-01-06 13:55 UTC, michael-koeller commented
p.s.: the paranthesis -> square brackets replacement in file setup.py resolved a warning issues by setuptools.

2021-02-08 14:16 UTC, michael-koeller commented
Hm, I didn't get any reactions on this pull-request. Are there perhaps any issues wit it?

2021-02-16 10:24 UTC, mroethke commented
I'm very sorry that I respond this late. I was and still am quite busy with other stuff and this just fell through the cracks.

It looks quite good at a quick glance but I would like to take a closer look before merging, I probably wont be able to do that before march though.

2021-03-08 11:07 UTC, mroethke requested changes
Please also rebase the commit on master

2021-03-08 11:07 UTC, mroethke commented on setup.py
> +    classifiers=[
please remove these changes from the commit

2021-03-08 11:07 UTC, mroethke commented on tests/test_pfx_table.py
> +AS_INVALID = 16
I think it would be clearer like this:
```suggestion
VALID = 1 << 0
INVALID = 1 << 1
UNKNOWN = 1 << 2
LENGTH_INVALID = 1 << 3
AS_INVALID = 1 << 4
```

2021-03-09 14:10 UTC, michael-koeller commented
Done.


> Am 08.03.2021 um 12:08 schrieb Marcel Röthke <notifications@github.com>:
> 
> 
> @mroethke requested changes on this pull request.
> 
> Please also rebase the commit on master
> 
> In setup.py <https://github.com/rtrlib/python-binding/pull/15#discussion_r589334402>:
> 
> > @@ -24,7 +24,7 @@
>      include_package_data=True,
>      license='MIT',
>      zip_safe=False,
> -    classifiers=(
> +    classifiers=[
> please remove these changes from the commit
> 
> In tests/test_pfx_table.py <https://github.com/rtrlib/python-binding/pull/15#discussion_r589336132>:
> 
> > +VALID = 1
> +INVALID = 2
> +UNKNOWN = 4
> +LENGTH_INVALID = 8
> +AS_INVALID = 16
> I think it would be clearer like this:
> 
> ⬇️ Suggested change
> -VALID = 1
> -INVALID = 2
> -UNKNOWN = 4
> -LENGTH_INVALID = 8
> -AS_INVALID = 16
> +VALID = 1 << 0
> +INVALID = 1 << 1
> +UNKNOWN = 1 << 2
> +LENGTH_INVALID = 1 << 3
> +AS_INVALID = 1 << 4
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/rtrlib/python-binding/pull/15#pullrequestreview-606172555>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AALKVDLQE3RR7RR7VYYTNHTTCSVZHANCNFSM4VXR7VFQ>.
>

2021-03-10 08:48 UTC, mroethke approved these changes
Looks good now.

Can you squash and do one final rebase to resolve the conflict?

2021-03-10 09:16 UTC, michael-koeller commented
OK, I squashed the two commits into one.

2021-03-10 09:46 UTC, merged

2021-03-10 09:46 UTC, mroethke commented
Great! Thank you!